import puppeteer from "puppeteer-core";
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true });
const page = await browser.newPage();
await page.setViewport({ width: 1100, height: 1000 });
await page.goto("http://localhost:5180/apply", { waitUntil: "networkidle0" });
await page.waitForSelector("form", { timeout: 20000 });
await page.screenshot({ path: ".context/apply-form.png" });
await page.click("button[type=submit]");
await page.waitForFunction(() => document.body.innerText.includes("Thanks, Jordan"), { timeout: 20000 });
await new Promise((r) => setTimeout(r, 500));
await page.screenshot({ path: ".context/apply-done.png" });
await browser.close();
console.log("e2e ok");
