import puppeteer from "puppeteer-core";
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true });
const page = await browser.newPage();
await page.setViewport({ width: 1100, height: 1000 });
await page.goto("http://localhost:5180/apply/backend-engineer", { waitUntil: "networkidle0" });
await page.waitForSelector("form", { timeout: 20000 });
await page.screenshot({ path: ".context/apply-form.png" });
const type = async (label, v) => { const h = await page.$(`xpath/.//label[normalize-space()='${label}']/following-sibling::*[1]`); await h.type(v); };
await type("Full name", "Inês Carvalho");
await type("Email", "ines.carvalho@proton.me");
await type("Phone, for the screening call", "+351 91 555 0142");
await type("City", "Porto");
await type("LinkedIn", "https://linkedin.com/in/inescarvalho");
await type("GitHub or portfolio", "https://github.com/inescarvalho");
const fileInput = await page.$('input[type=file]');
await fileInput.uploadFile(".context/cv.pdf");
await page.select("select", "yes");
await type("Earliest start date", "2 months notice");
await type("Anything you want us to know", "Currently at a fintech in Porto, mostly Go and Postgres. Happy to do the call after 17:00.");
await page.click("button[type=submit]");
await page.waitForFunction(() => document.body.innerText.includes("Thanks, Inês"), { timeout: 20000 });
await new Promise((r) => setTimeout(r, 500));
await page.screenshot({ path: ".context/apply-done.png" });
// admin side
await page.setViewport({ width: 1440, height: 1000 });
await page.goto("http://localhost:5180/", { waitUntil: "networkidle0" });
await page.waitForSelector(".mode button:last-child"); await page.click(".mode button:last-child");
await page.waitForSelector(".col.s0 .card", { timeout: 20000 });
await page.click(".col.s0 .card");
await new Promise((r) => setTimeout(r, 900));
await page.screenshot({ path: ".context/apply-admin.png" });
await browser.close();
console.log("e2e ok");
